### ISSUE TITLE
springboot actuator endpoint /refresh is causing CPU spike with spring-cloud-config-client

### ISSUE THREAD

**Issue by rajanigk** [spring-guides/gs-centralized-configuration#28]
we are using spring-cloud-config-server with s3 backend. When we do config refresh using the actutor endpoint refresh, in the spring boot application using spring-cloud-config-client library, we see huge CPU spike. it is requiring atleast 7-8 times the normal CPU needed by the application. Is this behaviour expected? I observed this CPU spike even if we have not used @RefreshScope in any class to absorb the dynamic config change.

**Comment by Buzzardo** [comment]
You should open this issue in the Spring Boot project.
