### ISSUE TITLE
Error: Cannot clone or checkout repository

### ISSUE THREAD

**Issue by ericis** [spring-guides/gs-centralized-configuration#3]
error: "java.lang.IllegalStateException: Cannot clone or checkout repository"

System: Win 10 Enterprise, Java 8

Steps to reproduce: clone client and service from git repo, create new local git repo for config settings under "Desktop\config", create "a-bootiful-client.properties" file and commit, start "configuration-service", check "/health" endpoint.

```
{
status: "DOWN",
configServer: {
status: "DOWN",
repository: {
application: "app",
profiles: "default"
},
error: "java.lang.IllegalStateException: Cannot clone or checkout repository"
},
diskSpace: {
status: "UP",
total: 509419655168,
free: 284697497600,
threshold: 10485760
},
refreshScope: {
status: "UP"
}
}
```

**Comment by ericis** [comment]
I tried running as Admin too, to see if that was the issue.

**Comment by ericis** [comment]
Had to add `file://${user.home}/` prefix to the uri in the server example.

So, in the last code part of the [initial section](https://spring.io/guides/gs/centralized-configuration/#initial), I updated the settings to be:

```
server.port=8888

spring.cloud.config.server.git.uri=file://${user.home}/Desktop/config
```

This was based on what I read in the [quick start documentation](https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc) that suggested the `file://` prefix in the uri.

**Comment by Brandon0204** [comment]
having same problem

**Comment by nitinkunal** [comment]
same here

**Comment by gregturn** [comment]
@dsyer Care to inspect this issue (or delegate to another member of your team?)

**Comment by nitinkunal** [comment]
issue resolved .

**Comment by lucoxlee** [comment]
same here,how did you solve it

**Comment by dsyer** [comment]
Works for me still. You do have to actually create a git repository (I added a note to clarify that in the README).

**Comment by mljohns89** [comment]
I was able to fix this with: 

spring.cloud.config.server.git.uri=file:///C:/path/to/config/repo/

If you want to make sure that your path is correct and can be picked up by spring, you can c/p the same path into a web browser.  This should give you a directory list.

I was not able to get working with ${HOME}.  I had to specify the full path.

For me specifically, I put my config repo in:
C:/Users/mjohns39/Documents/config

And the value I put for the spring property is:

file:///C:/Users/mjohns39/Documents/config

Again, you can c/p this value (include "file") into chrome to check syntax.

**Comment by Pramodgowdam** [comment]
when i try to send request to my github to test spring cloud, I am getting ### Cannot clone or checkout repository error. Could you please help me.

**Comment by dsyer** [comment]
@Pramodgowdam that’s not really enough information to tell what you did or when the error happened.

**Comment by Pramodgowdam** [comment]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Feb 23 12:21:14 EST 2018
There was an unexpected error (type=Not Found, status=404).
Cannot clone or checkout repository: https://github.com/Pramodgowdam/spring-cloud-properties

**Comment by dsyer** [comment]
More detail would still be useful. That link is to a public repository though, so I expect the most likely thing to go wrong would be a network issue in your environment. Are you behind a firewall or proxy?

**Comment by Pramodgowdam** [comment]
I was behind firewall, So I was getting that error. Thanks for responding.

**Comment by ghost** [comment]
same issue ,the termial shows javax.ws.rs.WebApplicationException: null  and thw web tells cant check or clone the git  from .... do u know why?

**Comment by techhb** [comment]
same isuse.

**Comment by ariaenggar** [comment]
@dsyer so the "git commit" was sufficient and we didn't required to do "git push"?

**Comment by dsyer** [comment]
Wrong place for usage questions. Git commit is sufficient to expose changes if the repo is in a local file.

**Comment by bommavj** [comment]
JGitEnvironmentRepository is unable to clone the repo as it is unable to find the exact path:
Added the url as below and it is able to clone the repo and shown the content in the properties file

spring.cloud.config.server.git.uri=file://C:/Users/vijay/Desktop/my-config

**Comment by imbarunsingh** [comment]
I also faced a similar problem with spring cloud config server. You need to add an additional property spring.cloud.config.server.git.skip-ssl-validation=true in application.properties file.
Checkout : https://stackoverflow.com/questions/50109704/spring-cloud-config-cannot-clone-or-checkout-repository-ssh-gitgithub-com

**Comment by imbarunsingh** [comment]
I also faced a similar problem with spring cloud config server. You need to add an additional property spring.cloud.config.server.git.skip-ssl-validation=true in application.properties file.
Checkout : https://stackoverflow.com/questions/50109704/spring-cloud-config-cannot-clone-or-checkout-repository-ssh-gitgithub-com

**Comment by wx409475835** [comment]
How to reslove this problem?

**Comment by erikzonz** [comment]
Help, please
![Error](https://user-images.githubusercontent.com/24423572/111363557-d2afa280-8655-11eb-9b26-d484083f45b4.png)

**Comment by hendisantika** [comment]
Now I have errors again. As follow:
It is said: 
```
https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/configuration: 422 Unprocessable Entity

2021-05-09 10:08:11.007  WARN 28080 --- [nio-8888-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.cloud.config.server.environment.NoSuchRepositoryException: Cannot clone or checkout repository: https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/configuration]

```

But, When I change config from `spring.cloud.config.server.git.uri=https://gitlab.com/microservice-samples/micro-services-spring-cloud-config/configuration` to `spring.cloud.config.server.git.uri=file://${user.home}/Desktop/tes/configuration`

it works.

Then If I change properties file to yml it error again.

Any suggestion?

Thanks

**Comment by alokjha933** [comment]
Make the repository public instead of private.
