### ISSUE TITLE
POST to http://localhost:8080/refresh results in 401 Unauthorized

### ISSUE THREAD

**Issue by ziadloo** [spring-guides/gs-centralized-configuration#5]
The [Spring guide](https://spring.io/guides/gs/centralized-configuration/) says that we should be able to refresh the client by sending a POST request to http://localhost:8080/refresh but doing so will result in an unauthorized 401 response.

`$ curl -X POST http://localhost:8080/refresh
{"timestamp":1487113045770,"status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource.","path":"/refresh"}`

**Comment by gregturn** [comment]
Possibly due to 1.5.1 locking down actuator by default. Comments @dsyer?

**Comment by dsyer** [comment]
Yes that would be it. I guess we need `management.security.enabled=false` for this guide.

**Comment by Cepr0** [comment]
> we need management.security.enabled=false for this guide.
Thanks @dsyer, that helped!

**Comment by alibaseit** [comment]
Thanks 
management.security.enabled=false
solved my problem too.

**Comment by dulipchandana** [comment]
management.security.enabled=false

**Comment by mahamafzar** [comment]
> management.security.enabled=false

So anyone can restart your service from your endpoint!

**Comment by robertomanfreda** [comment]
> Yes that would be it. I guess we need `management.security.enabled=false` for this guide.

Don't do that! Anyone who guess ip and port of your microservice could take the control! For example he can see your configprops calling /actuator/configprops, or inspect the env and other stuff!
