### ISSUE TITLE
In spring cloud client when refresh method is posted (http://localhost:8080/refresh) got below error message

### ISSUE THREAD

**Issue by huhailang9012** [spring-guides/gs-centralized-configuration#7]
In spring cloud client when refresh method is posted (http://localhost:8080/refresh) got below error message.
    `{
      "timestamp": "2018-03-25T14:46:21.170+0000",
      "status": 404,
      "error": "Not Found",
      "message": "No message available",
      "path": "/refresh"
    }`
    The following is version information:
    Spring Boot: 2.0.0.RELEASE Spring Cloud: Finchley.M8
    later on, I tried to use the demo gs-centralized-configuration but it turned out to be the same error.

**Comment by mohitsinha** [comment]
I am facing the same issue when using Finchley.M8

**Comment by galileo2008** [comment]
server:
  port: 8093 #设置对外服务的端口号
management:
  server:
    port: 5000
  health:
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - refresh
 
curl.exe -X POST http://localhost:5000/actuator/refresh
