### ISSUE TITLE
Wrong gradle version set for configuration-client sub project

### ISSUE THREAD

**Issue by joc-mer** [spring-guides/gs-centralized-configuration#8]
Here is the error I have when I try to build configuration-client from gradlew :

```
$ ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/joc/Dev/repos/gs-centralized-configuration/initial/configuration-client/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':configuration-client'.
> Failed to apply plugin [id 'org.springframework.boot']
   > Spring Boot plugin requires Gradle 4.0 or later. The current version is Gradle 2.13
```

**Comment by gregturn** [comment]
That's actually an inconsistency with the "complete" version of things. There is no maven or gradle wrapper on each individual project since the guide presumes you're building both at once.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-centralized-configuration/commit/2ca25c1577d72c88059fdc928601714fd24fda09
